FROM mlinarik/minecraft:paper-1.21_20250221.1

# Map plugin: https://www.spigotmc.org/resources/pl3xmap.109697/
ADD https://cdn.modrinth.com/data/34T8oVNY/versions/OvwBThgN/Pl3xMap-1.21.4-521.jar /mcdata/plugins

# Adding Whitelist
ADD whitelist.json /mcdata/whitelist.json