FROM itzg/minecraft-server:2025.2.1

# Map plugin: https://www.spigotmc.org/resources/pl3xmap.109697/
ADD https://cdn.modrinth.com/data/34T8oVNY/versions/OvwBThgN/Pl3xMap-1.21.4-521.jar /data/plugins

# Adding Whitelist
ADD whitelist.json /data/whitelist.json