networks:
  proxy:
    external: true

services:
  minecraft:
    image: itzg/minecraft-server:2025.2.1
    ports:
      - '25565:25565'
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 5s
      retries: 20
    volumes:
      - neverendranche:/data:rw
    networks:
      - proxy
    environment:
      MODRINTH_PROJECTS: "34T8oVNY:beta,fALzjamp"
      TYPE: "PAPER"
      EULA: "True"
      MEMORY: "6G"
      DIFFICULTY: "normal"
      ENABLE_QUERY: "false"
      MAX_PLAYERS: "10"
      ALLOW_NETHER: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      FORCE_GAMEMODE: "true"
      GENERATE_STRUCTURES: "true"
      HARDCORE: "false"
      SPAWN_ANIMALS: "true"
      SPAWN_NPCS: "true"
      SPAWN_PROTECTION: 1
      VIEW_DISTANCE: 16
      SEED: Neverendranche
      MODE: "survival"
      PVP: "true"
      ALLOW_FLIGHT: "false"
      SERVER_NAME: "Neverendranche"
      WHITELIST: |
        Decoup
        TheCroc420
        KingIngeborg
        derShwabe
        McPaul10
        Skornexs
        j03rn
      OPS: | 
        Decoup

    labels:
      backup: true
      traefik.enable: true
      
      traefik.http.middlewares.neverendranche-https-redirect.redirectscheme.scheme: https
      
      traefik.http.routers.neverendranche.entrypoints: http
      traefik.http.routers.neverendranche.rule: Host(`neverendranche.gamepus.net`)
      traefik.http.routers.neverendranche.middlewares: neverendranche-https-redirect

      traefik.http.routers.neverendranche-secure.entrypoints: https
      traefik.http.routers.neverendranche-secure.rule: Host(`neverendranche.gamepus.net`)
      traefik.http.routers.neverendranche-secure.tls: true
      traefik.http.routers.neverendranche-secure.tls.certresolver: http
      traefik.http.routers.neverendranche-secure.service: neverendranche
      #traefik.http.routers.neverendranche-secure.middlewares: secHeaders@file
      traefik.http.services.neverendranche.loadbalancer.server.port: 8080
      traefik.docker.network: proxy

volumes:
  neverendranche:
