services:
  minecraft:
    image: itzg/minecraft-server:latest
    ports:
      - '25565:25565'
      - '8080:8080'
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 5s
      retries: 20
    volumes:
      - neverendranche_v3:/data:rw
    environment:
      TYPE: "PAPER"
      VERSION: 1.21.10
      MODRINTH_PROJECTS: |
        pl3xmap:1.21.10-537
      EULA: "True"
      MEMORY: "24G"
      DIFFICULTY: "normal"
      ENABLE_QUERY: "false"
      MAX_PLAYERS: "10"
      ALLOW_NETHER: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      FORCE_GAMEMODE: "true"
      GENERATE_STRUCTURES: "true"
      HARDCORE: "false"
      SPAWN_ANIMALS: "true"
      SPAWN_NPCS: "true"
      SPAWN_PROTECTION: 1
      VIEW_DISTANCE: 16
      SEED: Macheinfachohnemithezrirgendeinmuell
      MODE: "survival"
      PVP: "true"
      ALLOW_FLIGHT: "false"
      SERVER_NAME: "MIT ♥"
      WHITELIST: |
        Decoup
        TheCroc420
        KingIngeborg
        derShwabe
        McPaul10
        Skornexs
        j03rn
        DerSureno
        Hatred_69
        NussbaumVirus
        Herobrine
        Blaulix
        aka_Konny
      OPS: 
      MOTD: |
        Version: 1.21.10
        Map: https://minecraft.mit-herz.org/

volumes:
  neverendranche_v3:
