networks:
  proxy:
    external: true

services:
  minecraft:
    image: itzg/minecraft-server:2025.2.1
    ports:
      - '25565:25565'
    volumes:
      - neverendranche:/data:rw
    networks:
      - proxy
    environment:
      MODRINTH_PROJECTS: "fabric-api:34T8oVNY"
      EULA: "True"
      DIFFICULTY: "hard"
      ENABLE_QUERY: "false"
      MAX_PLAYERS: "10"
      ALLOW_NETHER: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      FORCE_GAMEMODE: "true"
      GENERATE_STRUCTURES: "true"
      HARDCORE: "false"
      SPAWN_ANIMALS: "true"
      SPAWN_NPCS: "true"
      SPAWN_PROTECTION: 1
      SEED: 987126986501
      MODE: "survival"
      PVP: "true"
      ALLOW_FLIGHT: "false"
      SERVER_NAME: "Neverendranche"
      WHITELIST: |
        Decoup
        The Croc9338
        KingIngeborg123

    labels:
      backup: true
      traefik.enable: true
      
      traefik.http.middlewares.neverendranche-https-redirect.redirectscheme.scheme: https
      
      traefik.http.routers.neverendranche.entrypoints: http
      traefik.http.routers.neverendranche.rule: Host(`neverendranche.gamepus.net`)
      traefik.http.routers.neverendranche.middlewares: neverendranche-https-redirect

      traefik.http.routers.neverendranche-secure.entrypoints: https
      traefik.http.routers.neverendranche-secure.rule: Host(`neverendranche.gamepus.net`)
      traefik.http.routers.neverendranche-secure.tls: true
      traefik.http.routers.neverendranche-secure.tls.certresolver: http
      traefik.http.routers.neverendranche-secure.service: neverendranche
      traefik.http.routers.neverendranche-secure.middlewares: secHeaders@file
      traefik.http.services.neverendranche.loadbalancer.server.port: 8080
      traefik.docker.network: proxy

volumes:
  neverendranche:
